/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import java.awt.BorderLayout;

/**
 *
 * @author jhose
 */
public class PamCrearUsuario extends javax.swing.JPanel {

    private final javax.swing.ButtonGroup buttonGroupOpciones;
    
    /**
     * Creates new form PamCrearUsuario
     */
    public PamCrearUsuario() {
        initComponents();
        buttonGroupOpciones = new javax.swing.ButtonGroup();
        buttonGroupOpciones.add(jrbCuentaCorriente);
        buttonGroupOpciones.add(jrbCuentaAhorro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        jrbCuentaCorriente = new javax.swing.JRadioButton();
        jrbCuentaAhorro = new javax.swing.JRadioButton();
        panContenido = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1284, 784));

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        //panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbCuentaCorriente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbCuentaCorriente.setForeground(new java.awt.Color(0, 51, 255));
        jrbCuentaCorriente.setText("Cuenta corriente");
        jrbCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCuentaCorrienteActionPerformed(evt);
            }
        });
        panBlanco.add(jrbCuentaCorriente);

        jrbCuentaAhorro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbCuentaAhorro.setForeground(new java.awt.Color(0, 51, 255));
        jrbCuentaAhorro.setText("Cuenta ahorro");
        jrbCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCuentaAhorroActionPerformed(evt);
            }
        });
        panBlanco.add(jrbCuentaAhorro);

        panContenido.setBackground(new java.awt.Color(255, 255, 255));
        panContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panContenido.setPreferredSize(new java.awt.Dimension(1136, 576));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido);
        panContenido.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCuentaCorrienteActionPerformed
        PanCrearCuentaCorriente panCrearCuentaCorriente = new PanCrearCuentaCorriente();
        panCrearCuentaCorriente.setSize(1136,576);
        panCrearCuentaCorriente.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(panCrearCuentaCorriente,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbCuentaCorrienteActionPerformed

    private void jrbCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCuentaAhorroActionPerformed
        PanCrearCuentaAhorro panCrearCuentaAhorro = new PanCrearCuentaAhorro();
        panCrearCuentaAhorro.setSize(1136,576);
        panCrearCuentaAhorro.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(panCrearCuentaAhorro,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbCuentaAhorroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jrbCuentaAhorro;
    private javax.swing.JRadioButton jrbCuentaCorriente;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    // End of variables declaration//GEN-END:variables
}
