/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import java.awt.BorderLayout;
import javax.swing.ButtonGroup;

import components.Employee;
/**
 *
 * @author jhose
 */
public class PamCrearPersona extends javax.swing.JPanel {

    private final javax.swing.ButtonGroup buttonGroupOpciones;
    
    /**
     * Creates new form PamCrearUsuario
     */

	private Employee comp;
    public PamCrearPersona(Employee comp) {
		this.comp = comp;
        initComponents();
        buttonGroupOpciones = new ButtonGroup();
        buttonGroupOpciones.add(jrdNatural);
        buttonGroupOpciones.add(jrbJuridica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        jrdNatural = new javax.swing.JRadioButton();
        jrbJuridica = new javax.swing.JRadioButton();
        panContenido = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1284, 784));

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrdNatural.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrdNatural.setForeground(new java.awt.Color(0, 51, 255));
        jrdNatural.setText("Persona Natural");
        jrdNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdNaturalActionPerformed(evt);
            }
        });
        panBlanco.add(jrdNatural, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jrbJuridica.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbJuridica.setForeground(new java.awt.Color(0, 51, 255));
        jrbJuridica.setText("Persona Juridica");
        jrbJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbJuridicaActionPerformed(evt);
            }
        });
        panBlanco.add(jrbJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        panContenido.setBackground(new java.awt.Color(204, 204, 204));
        panContenido.setPreferredSize(new java.awt.Dimension(1120, 680));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 760));
        panContenido.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbJuridicaActionPerformed
        PanCrearJuridico panCrearjur = new PanCrearJuridico(comp);
        panCrearjur.setSize(1100,670);
        panCrearjur.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(panCrearjur,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbJuridicaActionPerformed

    private void jrdNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdNaturalActionPerformed
        PanCrearNatural panCrearnat = new PanCrearNatural(comp);
        panCrearnat.setSize(1100,670);
        panCrearnat.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(panCrearnat,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrdNaturalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jrbJuridica;
    private javax.swing.JRadioButton jrdNatural;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    // End of variables declaration//GEN-END:variables
}
