/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import java.awt.Color;
import java.util.ArrayList;

import common.exceptions.ClientNotFound;
import common.logger.Logger;
import components.Employee;
import functions.stringFormatter;
import objects.accounts.Persona;

/**
 *
 * @author edu11
 */
public class PanCrearCuentaCorriente extends javax.swing.JPanel {

    /**
     * Creates new form PanCrearCuentaAhorro2
     */
	private Employee comp;
    public PanCrearCuentaCorriente(Employee comp) {
		this.comp = comp;
        initComponents();
		cmbRepresentante.removeAllItems();
		for(String i: comp.getListaNrosDoc()){
			cmbRepresentante.addItem(i);
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panSaldoInicial = new javax.swing.JPanel();
        lblSaldoInicial = new javax.swing.JLabel();
        txtSaldoInicial = new javax.swing.JTextField();
        panTipoMoneda = new javax.swing.JPanel();
        lblTipoMoneda = new javax.swing.JLabel();
        txtTipoMoneda = new javax.swing.JTextField();
        panTitularDeLaCuenta = new javax.swing.JPanel();
        lblTitularDeLaCuenta = new javax.swing.JLabel();
        cmbRepresentante = new javax.swing.JComboBox<>();
        panInteresAplicado = new javax.swing.JPanel();
        lblInteresAplicado = new javax.swing.JLabel();
        txtInteresAplicado = new javax.swing.JTextField();
        panLimiteSobregiro = new javax.swing.JPanel();
        lblLimiteSobregiro = new javax.swing.JLabel();
        txtLimiteSobregiro = new javax.swing.JTextField();
        panLimiteCheques = new javax.swing.JPanel();
        lblLimiteCheques = new javax.swing.JLabel();
        txtLimiteCheques = new javax.swing.JTextField();
        panComisionPorCheque = new javax.swing.JPanel();
        lblComisionPorCheque = new javax.swing.JLabel();
        txtComisionPorCheque = new javax.swing.JTextField();
        txtCommisPorCheque = new javax.swing.JTextField();
        jbtGuardar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1120, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaldoInicial.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblSaldoInicial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaldoInicial.setText("SALDO INICIAL");
        lblSaldoInicial.setAlignmentX(0.5F);
        lblSaldoInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtSaldoInicial.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSaldoInicial.setForeground(new java.awt.Color(204, 204, 204));
        txtSaldoInicial.setText("...");
        txtSaldoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSaldoInicialLayout = new javax.swing.GroupLayout(panSaldoInicial);
        panSaldoInicial.setLayout(panSaldoInicialLayout);
        panSaldoInicialLayout.setHorizontalGroup(
            panSaldoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSaldoInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSaldoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        panSaldoInicialLayout.setVerticalGroup(
            panSaldoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSaldoInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSaldoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panSaldoInicialLayout.createSequentialGroup()
                        .addComponent(txtSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 920, 40));

        lblTipoMoneda.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblTipoMoneda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoMoneda.setText("TIPO DE MONEDA");
        lblTipoMoneda.setAlignmentX(0.5F);
        lblTipoMoneda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtTipoMoneda.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTipoMoneda.setForeground(new java.awt.Color(204, 204, 204));
        txtTipoMoneda.setText("...");
        txtTipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoMonedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTipoMonedaLayout = new javax.swing.GroupLayout(panTipoMoneda);
        panTipoMoneda.setLayout(panTipoMonedaLayout);
        panTipoMonedaLayout.setHorizontalGroup(
            panTipoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTipoMonedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        panTipoMonedaLayout.setVerticalGroup(
            panTipoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTipoMonedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTipoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panTipoMonedaLayout.createSequentialGroup()
                        .addComponent(txtTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panTipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 920, 40));

        lblTitularDeLaCuenta.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblTitularDeLaCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitularDeLaCuenta.setText("TITULAR DE LA CUENTA");
        lblTitularDeLaCuenta.setAlignmentX(0.5F);
        lblTitularDeLaCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmbRepresentante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panTitularDeLaCuentaLayout = new javax.swing.GroupLayout(panTitularDeLaCuenta);
        panTitularDeLaCuenta.setLayout(panTitularDeLaCuentaLayout);
        panTitularDeLaCuentaLayout.setHorizontalGroup(
            panTitularDeLaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitularDeLaCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitularDeLaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        panTitularDeLaCuentaLayout.setVerticalGroup(
            panTitularDeLaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTitularDeLaCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTitularDeLaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitularDeLaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(cmbRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panTitularDeLaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 920, 40));

        lblInteresAplicado.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblInteresAplicado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInteresAplicado.setText("INTERES APLICADO");
        lblInteresAplicado.setAlignmentX(0.5F);
        lblInteresAplicado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtInteresAplicado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtInteresAplicado.setForeground(new java.awt.Color(204, 204, 204));
        txtInteresAplicado.setText("...");
        txtInteresAplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteresAplicadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInteresAplicadoLayout = new javax.swing.GroupLayout(panInteresAplicado);
        panInteresAplicado.setLayout(panInteresAplicadoLayout);
        panInteresAplicadoLayout.setHorizontalGroup(
            panInteresAplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInteresAplicadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInteresAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInteresAplicado, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        panInteresAplicadoLayout.setVerticalGroup(
            panInteresAplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInteresAplicadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInteresAplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInteresAplicado, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(panInteresAplicadoLayout.createSequentialGroup()
                        .addComponent(txtInteresAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panInteresAplicado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 920, 40));

        lblLimiteSobregiro.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteSobregiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteSobregiro.setText("LIMITE DE SOBREGIRO");
        lblLimiteSobregiro.setAlignmentX(0.5F);
        lblLimiteSobregiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLimiteSobregiro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLimiteSobregiro.setForeground(new java.awt.Color(204, 204, 204));
        txtLimiteSobregiro.setText("...");
        txtLimiteSobregiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteSobregiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteSobregiroLayout = new javax.swing.GroupLayout(panLimiteSobregiro);
        panLimiteSobregiro.setLayout(panLimiteSobregiroLayout);
        panLimiteSobregiroLayout.setHorizontalGroup(
            panLimiteSobregiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteSobregiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteSobregiro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLimiteSobregiro, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteSobregiroLayout.setVerticalGroup(
            panLimiteSobregiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteSobregiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteSobregiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLimiteSobregiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panLimiteSobregiroLayout.createSequentialGroup()
                        .addComponent(txtLimiteSobregiro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panLimiteSobregiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 920, 40));

        lblLimiteCheques.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques.setText("LIMITE DE CHEQUEZ");
        lblLimiteCheques.setAlignmentX(0.5F);
        lblLimiteCheques.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLimiteCheques.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLimiteCheques.setForeground(new java.awt.Color(204, 204, 204));
        txtLimiteCheques.setText("...");
        txtLimiteCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteChequesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteChequesLayout = new javax.swing.GroupLayout(panLimiteCheques);
        panLimiteCheques.setLayout(panLimiteChequesLayout);
        panLimiteChequesLayout.setHorizontalGroup(
            panLimiteChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteChequesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLimiteCheques, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteChequesLayout.setVerticalGroup(
            panLimiteChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteChequesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLimiteCheques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panLimiteChequesLayout.createSequentialGroup()
                        .addComponent(txtLimiteCheques, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 920, 40));

        lblComisionPorCheque.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblComisionPorCheque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComisionPorCheque.setText("COMISION POR CHEQUE");
        lblComisionPorCheque.setAlignmentX(0.5F);
        lblComisionPorCheque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtComisionPorCheque.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtComisionPorCheque.setForeground(new java.awt.Color(204, 204, 204));
        txtComisionPorCheque.setText("...");
        txtComisionPorCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComisionPorChequeActionPerformed(evt);
            }
        });

        txtCommisPorCheque.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCommisPorCheque.setForeground(new java.awt.Color(204, 204, 204));
        txtCommisPorCheque.setText("...");
        txtCommisPorCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommisPorChequeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panComisionPorChequeLayout = new javax.swing.GroupLayout(panComisionPorCheque);
        panComisionPorCheque.setLayout(panComisionPorChequeLayout);
        panComisionPorChequeLayout.setHorizontalGroup(
            panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComisionPorChequeLayout.createSequentialGroup()
                .addGroup(panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panComisionPorChequeLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(txtComisionPorCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                    .addGroup(panComisionPorChequeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblComisionPorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtCommisPorCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panComisionPorChequeLayout.setVerticalGroup(
            panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComisionPorChequeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComisionPorCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCommisPorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtComisionPorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panComisionPorCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 920, 40));

        jbtGuardar.setBackground(new java.awt.Color(51, 51, 255));
        jbtGuardar.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jbtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbtGuardar.setText("GUARDAR");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoInicialActionPerformed
    }//GEN-LAST:event_txtSaldoInicialActionPerformed

    private void txtTipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoMonedaActionPerformed
    }//GEN-LAST:event_txtTipoMonedaActionPerformed

    private void txtInteresAplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteresAplicadoActionPerformed
    }//GEN-LAST:event_txtInteresAplicadoActionPerformed

    private void txtLimiteSobregiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteSobregiroActionPerformed
    }//GEN-LAST:event_txtLimiteSobregiroActionPerformed

    private void txtLimiteChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteChequesActionPerformed
    }//GEN-LAST:event_txtLimiteChequesActionPerformed

    private void txtCommisPorChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommisPorChequeActionPerformed
    }//GEN-LAST:event_txtCommisPorChequeActionPerformed

    private void txtComisionPorChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComisionPorChequeActionPerformed
    }//GEN-LAST:event_txtComisionPorChequeActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
		float overdraftLimit;
	try{
		 overdraftLimit = Float.parseFloat(txtLimiteSobregiro.getText());}
	catch (Exception e) {
		overdraftLimit = 50000.0f;
	}
	float chequeLimit;
	try
	{chequeLimit = Float.parseFloat(txtLimiteCheques.getText());}
	catch (Exception e) {
		chequeLimit = 10000.0f;
	}
	float chequeNumberLimit;
	try
	{ chequeNumberLimit = Float.parseFloat(txtNumeroCheques1.getText());}
	catch (Exception e) {
		chequeNumberLimit = 100.0f;
	}
	float chequeCommission;
	try
	{chequeCommission = Float.parseFloat(txtComisionPorCheque.getText());}
	catch (Exception e) {
		chequeCommission = 0.05f;
	}
	String year = Logger.dateString(0).substring(6,10);
	String month = Logger.dateString(0).substring(3,5);
	String day= Logger.dateString(0).substring(0,2);
	String currency = txtTipoMoneda.getText();
	double balance;
	try{ 
	balance = Double.parseDouble(txtSaldoInicial.getText());
	} catch (Exception e) {
		 balance = 0;
	}
	float interestRate = 0.05f;
	Persona rep;
	try {
		rep = comp.searchNatural((String)cmbRepresentante.getSelectedItem());
	} catch (ClientNotFound e) {
		try {
			rep = comp.searchJuridica((String)cmbRepresentante.getSelectedItem()).getRepresentative();
		} catch (ClientNotFound e1) {
			rep = new Persona(null, null, null, null, null, null, null, null, null);
		}
	}
	String id = rep.getIdString();
	String idtype = rep.getIdType();

	boolean status = comp.createCorriente(overdraftLimit, chequeLimit, chequeNumberLimit, stringFormatter.numberGeneratorCorriente(), chequeCommission, stringFormatter.numberGeneratorCorriente(), year, month, day, currency, balance, interestRate, id, idtype);
    if (status){
		jbtGuardar.setBackground(new Color(51, 51, 255));
	}
	else{
		jbtGuardar.setBackground(new Color(255, 51, 51));
	}

		
    }//GEN-LAST:event_jbtGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRepresentante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JLabel lblComisionPorCheque;
    private javax.swing.JLabel lblInteresAplicado;
    private javax.swing.JLabel lblLimiteCheques;
    private javax.swing.JLabel lblLimiteSobregiro;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JLabel lblTipoMoneda;
    private javax.swing.JLabel lblTitularDeLaCuenta;
    private javax.swing.JPanel panComisionPorCheque;
    private javax.swing.JPanel panInteresAplicado;
    private javax.swing.JPanel panLimiteCheques;
    private javax.swing.JPanel panLimiteSobregiro;
    private javax.swing.JPanel panSaldoInicial;
    private javax.swing.JPanel panTipoMoneda;
    private javax.swing.JPanel panTitularDeLaCuenta;
    private javax.swing.JTextField txtComisionPorCheque;
    private javax.swing.JTextField txtCommisPorCheque;
    private javax.swing.JTextField txtInteresAplicado;
    private javax.swing.JTextField txtLimiteCheques;
    private javax.swing.JTextField txtLimiteSobregiro;
    private javax.swing.JTextField txtSaldoInicial;
    private javax.swing.JTextField txtTipoMoneda;
    // End of variables declaration//GEN-END:variables
}
