/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

/**
 *
 * @author jhose
 */
public class PanCrearCuentaAhorro extends javax.swing.JPanel {

    /**
     * Creates new form PanCrearCuentaAhorro
     */
    public PanCrearCuentaAhorro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        txtTipoMoneda = new javax.swing.JTextField();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtFechaApertura = new javax.swing.JTextField();
        TxtTitularCuenta = new javax.swing.JTextField();
        txtInteresAplicado = new javax.swing.JTextField();
        txtLimiteRetiros = new javax.swing.JTextField();
        txtFechaCortes = new javax.swing.JTextField();
        TxtBeneficiarios = new javax.swing.JTextField();
        txtSaldoInicial = new javax.swing.JTextField();
        txtIngresoFechaApertura = new javax.swing.JTextField();
        txtIngresoSaldoInicial = new javax.swing.JTextField();
        txtIngresoTipoMoneda = new javax.swing.JTextField();
        txtIngresoTitularCuenta = new javax.swing.JTextField();
        txtIngresoInteresAplicado = new javax.swing.JTextField();
        txtIngresoLimiteRetiros = new javax.swing.JTextField();
        txtIngresoFechaCorte = new javax.swing.JTextField();
        txtIngresoBeneficiarios = new javax.swing.JTextField();
        txtIngresoNumeroCuenta = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1136, 576));
        //panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipoMoneda.setBackground(new java.awt.Color(0, 102, 255));
        txtTipoMoneda.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtTipoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoMoneda.setText("Tipo de moneda");
        txtTipoMoneda.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtTipoMoneda);

        txtNumeroCuenta.setBackground(new java.awt.Color(0, 102, 255));
        txtNumeroCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtNumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroCuenta.setText("Numero de cuenta");
        txtNumeroCuenta.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtNumeroCuenta);

        txtFechaApertura.setBackground(new java.awt.Color(0, 102, 255));
        txtFechaApertura.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtFechaApertura.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaApertura.setText("Fecha de apertura");
        txtFechaApertura.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtFechaApertura);

        TxtTitularCuenta.setBackground(new java.awt.Color(0, 102, 255));
        TxtTitularCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        TxtTitularCuenta.setForeground(new java.awt.Color(255, 255, 255));
        TxtTitularCuenta.setText("Titular de la cuenta");
        TxtTitularCuenta.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(TxtTitularCuenta);

        txtInteresAplicado.setBackground(new java.awt.Color(0, 102, 255));
        txtInteresAplicado.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtInteresAplicado.setForeground(new java.awt.Color(255, 255, 255));
        txtInteresAplicado.setText("Interes aplicado");
        txtInteresAplicado.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtInteresAplicado);

        txtLimiteRetiros.setBackground(new java.awt.Color(0, 102, 255));
        txtLimiteRetiros.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtLimiteRetiros.setForeground(new java.awt.Color(255, 255, 255));
        txtLimiteRetiros.setText("Limite de retiros");
        txtLimiteRetiros.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtLimiteRetiros);

        txtFechaCortes.setBackground(new java.awt.Color(0, 102, 255));
        txtFechaCortes.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtFechaCortes.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaCortes.setText("Fecha de corte");
        txtFechaCortes.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtFechaCortes);

        TxtBeneficiarios.setBackground(new java.awt.Color(0, 102, 255));
        TxtBeneficiarios.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        TxtBeneficiarios.setForeground(new java.awt.Color(255, 255, 255));
        TxtBeneficiarios.setText("Beneficiarios");
        TxtBeneficiarios.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(TxtBeneficiarios);

        txtSaldoInicial.setBackground(new java.awt.Color(0, 102, 255));
        txtSaldoInicial.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtSaldoInicial.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldoInicial.setText("Saldo inicial");
        txtSaldoInicial.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtSaldoInicial);

        txtIngresoFechaApertura.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoFechaApertura.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoFechaApertura);

        txtIngresoSaldoInicial.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoSaldoInicial.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoSaldoInicial);

        txtIngresoTipoMoneda.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoTipoMoneda.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoTipoMoneda);

        txtIngresoTitularCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoTitularCuenta.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoTitularCuenta);

        txtIngresoInteresAplicado.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoInteresAplicado.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoInteresAplicado);

        txtIngresoLimiteRetiros.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoLimiteRetiros.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoLimiteRetiros);

        txtIngresoFechaCorte.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoFechaCorte.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoFechaCorte);

        txtIngresoBeneficiarios.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoBeneficiarios.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoBeneficiarios);

        txtIngresoNumeroCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoNumeroCuenta.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoNumeroCuenta);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_file.gif"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panBlanco.add(btnGuardar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtBeneficiarios;
    private javax.swing.JTextField TxtTitularCuenta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JTextField txtFechaApertura;
    private javax.swing.JTextField txtFechaCortes;
    private javax.swing.JTextField txtIngresoBeneficiarios;
    private javax.swing.JTextField txtIngresoFechaApertura;
    private javax.swing.JTextField txtIngresoFechaCorte;
    private javax.swing.JTextField txtIngresoInteresAplicado;
    private javax.swing.JTextField txtIngresoLimiteRetiros;
    private javax.swing.JTextField txtIngresoNumeroCuenta;
    private javax.swing.JTextField txtIngresoSaldoInicial;
    private javax.swing.JTextField txtIngresoTipoMoneda;
    private javax.swing.JTextField txtIngresoTitularCuenta;
    private javax.swing.JTextField txtInteresAplicado;
    private javax.swing.JTextField txtLimiteRetiros;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtSaldoInicial;
    private javax.swing.JTextField txtTipoMoneda;
    // End of variables declaration//GEN-END:variables
}
