/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import common.exceptions.ClientNotFound;
import common.exceptions.InvalidInput;
import common.logger.Logger;
import components.Employee;
import functions.stringFormatter;
import objects.accounts.Persona;

/**
 *
 * @author edu11
 */
public class PanCrearNatural extends javax.swing.JPanel {

    /**
     * Creates new form PanCrearCuentaAhorro2
     */
	private Employee comp;
    public PanCrearNatural(Employee comp) {
		this.comp = comp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panSaldoInicial = new javax.swing.JPanel();
        lblSaldoInicial = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        panTipoMoneda = new javax.swing.JPanel();
        lblTipoMoneda = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        panTitularDeLaCuenta = new javax.swing.JPanel();
        lblTitularDeLaCuenta = new javax.swing.JLabel();
        txtDocID = new javax.swing.JTextField();
        panInteresAplicado = new javax.swing.JPanel();
        lblInteresAplicado = new javax.swing.JLabel();
        txtDocType = new javax.swing.JTextField();
        panLimiteSobregiro = new javax.swing.JPanel();
        lblLimiteSobregiro = new javax.swing.JLabel();
        txtBirthYear = new javax.swing.JTextField();
        panLimiteCheques = new javax.swing.JPanel();
        lblLimiteCheques = new javax.swing.JLabel();
        txtBirthMonth = new javax.swing.JTextField();
        panComisionPorCheque = new javax.swing.JPanel();
        lblComisionPorCheque = new javax.swing.JLabel();
        txtComisionPorCheque = new javax.swing.JTextField();
        txtBirthDay = new javax.swing.JTextField();
        jbtGuardar = new javax.swing.JButton();
        panInteresAplicado1 = new javax.swing.JPanel();
        lblInteresAplicado1 = new javax.swing.JLabel();
        txtCivilStatus = new javax.swing.JTextField();
        panLimiteCheques1 = new javax.swing.JPanel();
        lblLimiteCheques1 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        panLimiteCheques2 = new javax.swing.JPanel();
        lblLimiteCheques2 = new javax.swing.JLabel();
        txtProvince = new javax.swing.JTextField();
        panLimiteCheques3 = new javax.swing.JPanel();
        lblLimiteCheques3 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        panLimiteCheques4 = new javax.swing.JPanel();
        lblLimiteCheques4 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        panLimiteCheques5 = new javax.swing.JPanel();
        lblLimiteCheques5 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        panLimiteCheques6 = new javax.swing.JPanel();
        lblLimiteCheques6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setPreferredSize(new java.awt.Dimension(1120, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaldoInicial.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblSaldoInicial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaldoInicial.setText("NOMBRES");
        lblSaldoInicial.setAlignmentX(0.5F);
        lblSaldoInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 204, 204));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSaldoInicialLayout = new javax.swing.GroupLayout(panSaldoInicial);
        panSaldoInicial.setLayout(panSaldoInicialLayout);
        panSaldoInicialLayout.setHorizontalGroup(
            panSaldoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSaldoInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panSaldoInicialLayout.setVerticalGroup(
            panSaldoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSaldoInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSaldoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 920, 40));

        lblTipoMoneda.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblTipoMoneda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoMoneda.setText("APELLIDOS");
        lblTipoMoneda.setAlignmentX(0.5F);
        lblTipoMoneda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtSurname.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSurname.setForeground(new java.awt.Color(204, 204, 204));
        txtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTipoMonedaLayout = new javax.swing.GroupLayout(panTipoMoneda);
        panTipoMoneda.setLayout(panTipoMonedaLayout);
        panTipoMonedaLayout.setHorizontalGroup(
            panTipoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTipoMonedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panTipoMonedaLayout.setVerticalGroup(
            panTipoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTipoMonedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTipoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panTipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 920, 40));

        lblTitularDeLaCuenta.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblTitularDeLaCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitularDeLaCuenta.setText("DOCUMENTO");
        lblTitularDeLaCuenta.setAlignmentX(0.5F);
        lblTitularDeLaCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDocID.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtDocID.setForeground(new java.awt.Color(204, 204, 204));
        txtDocID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTitularDeLaCuentaLayout = new javax.swing.GroupLayout(panTitularDeLaCuenta);
        panTitularDeLaCuenta.setLayout(panTitularDeLaCuentaLayout);
        panTitularDeLaCuentaLayout.setHorizontalGroup(
            panTitularDeLaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitularDeLaCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitularDeLaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDocID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(647, 647, 647))
        );
        panTitularDeLaCuentaLayout.setVerticalGroup(
            panTitularDeLaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTitularDeLaCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTitularDeLaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitularDeLaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtDocID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panTitularDeLaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 300, 40));

        lblInteresAplicado.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblInteresAplicado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInteresAplicado.setText("TIPO");
        lblInteresAplicado.setAlignmentX(0.5F);
        lblInteresAplicado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDocType.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtDocType.setForeground(new java.awt.Color(204, 204, 204));
        txtDocType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInteresAplicadoLayout = new javax.swing.GroupLayout(panInteresAplicado);
        panInteresAplicado.setLayout(panInteresAplicadoLayout);
        panInteresAplicadoLayout.setHorizontalGroup(
            panInteresAplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInteresAplicadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInteresAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDocType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panInteresAplicadoLayout.setVerticalGroup(
            panInteresAplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInteresAplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblInteresAplicado, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(txtDocType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panInteresAplicado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 200, 40));

        lblLimiteSobregiro.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteSobregiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteSobregiro.setText("AÑO NACIMIENTO");
        lblLimiteSobregiro.setAlignmentX(0.5F);
        lblLimiteSobregiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtBirthYear.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBirthYear.setForeground(new java.awt.Color(204, 204, 204));
        txtBirthYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteSobregiroLayout = new javax.swing.GroupLayout(panLimiteSobregiro);
        panLimiteSobregiro.setLayout(panLimiteSobregiroLayout);
        panLimiteSobregiroLayout.setHorizontalGroup(
            panLimiteSobregiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteSobregiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteSobregiro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panLimiteSobregiroLayout.setVerticalGroup(
            panLimiteSobregiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteSobregiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteSobregiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteSobregiro, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteSobregiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 40));

        lblLimiteCheques.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques.setText("MES NACIMIENTO");
        lblLimiteCheques.setAlignmentX(0.5F);
        lblLimiteCheques.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtBirthMonth.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBirthMonth.setForeground(new java.awt.Color(204, 204, 204));
        txtBirthMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteChequesLayout = new javax.swing.GroupLayout(panLimiteCheques);
        panLimiteCheques.setLayout(panLimiteChequesLayout);
        panLimiteChequesLayout.setHorizontalGroup(
            panLimiteChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteChequesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques)
                .addGap(18, 18, 18)
                .addComponent(txtBirthMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteChequesLayout.setVerticalGroup(
            panLimiteChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteChequesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteCheques, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 300, 40));

        lblComisionPorCheque.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblComisionPorCheque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComisionPorCheque.setText("DIA NACIMIENTO");
        lblComisionPorCheque.setAlignmentX(0.5F);
        lblComisionPorCheque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtComisionPorCheque.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtComisionPorCheque.setForeground(new java.awt.Color(204, 204, 204));
        txtComisionPorCheque.setText("...");
        txtComisionPorCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComisionPorChequeActionPerformed(evt);
            }
        });

        txtBirthDay.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBirthDay.setForeground(new java.awt.Color(204, 204, 204));
        txtBirthDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthDayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panComisionPorChequeLayout = new javax.swing.GroupLayout(panComisionPorCheque);
        panComisionPorCheque.setLayout(panComisionPorChequeLayout);
        panComisionPorChequeLayout.setHorizontalGroup(
            panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComisionPorChequeLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(txtComisionPorCheque)
                .addContainerGap())
            .addGroup(panComisionPorChequeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComisionPorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBirthDay)
                .addGap(51, 51, 51))
        );
        panComisionPorChequeLayout.setVerticalGroup(
            panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComisionPorChequeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panComisionPorChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComisionPorCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtComisionPorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panComisionPorCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 300, 40));

        jbtGuardar.setBackground(new java.awt.Color(51, 51, 255));
        jbtGuardar.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jbtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbtGuardar.setText("GUARDAR");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        lblInteresAplicado1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblInteresAplicado1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInteresAplicado1.setText("ESTADO CIVIL");
        lblInteresAplicado1.setAlignmentX(0.5F);
        lblInteresAplicado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtCivilStatus.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCivilStatus.setForeground(new java.awt.Color(204, 204, 204));
        txtCivilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCivilStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInteresAplicado1Layout = new javax.swing.GroupLayout(panInteresAplicado1);
        panInteresAplicado1.setLayout(panInteresAplicado1Layout);
        panInteresAplicado1Layout.setHorizontalGroup(
            panInteresAplicado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInteresAplicado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInteresAplicado1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panInteresAplicado1Layout.setVerticalGroup(
            panInteresAplicado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInteresAplicado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblInteresAplicado1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(txtCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panInteresAplicado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 400, 40));

        lblLimiteCheques1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques1.setText("REGION");
        lblLimiteCheques1.setAlignmentX(0.5F);
        lblLimiteCheques1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtRegion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRegion.setForeground(new java.awt.Color(204, 204, 204));
        txtRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteCheques1Layout = new javax.swing.GroupLayout(panLimiteCheques1);
        panLimiteCheques1.setLayout(panLimiteCheques1Layout);
        panLimiteCheques1Layout.setHorizontalGroup(
            panLimiteCheques1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteCheques1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques1)
                .addGap(18, 18, 18)
                .addComponent(txtRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteCheques1Layout.setVerticalGroup(
            panLimiteCheques1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteCheques1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteCheques1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteCheques1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 300, 40));

        lblLimiteCheques2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques2.setText("PROVINCIA");
        lblLimiteCheques2.setAlignmentX(0.5F);
        lblLimiteCheques2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtProvince.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtProvince.setForeground(new java.awt.Color(204, 204, 204));
        txtProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvinceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteCheques2Layout = new javax.swing.GroupLayout(panLimiteCheques2);
        panLimiteCheques2.setLayout(panLimiteCheques2Layout);
        panLimiteCheques2Layout.setHorizontalGroup(
            panLimiteCheques2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteCheques2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProvince, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteCheques2Layout.setVerticalGroup(
            panLimiteCheques2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteCheques2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteCheques2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteCheques2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 300, 40));

        lblLimiteCheques3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques3.setText("DISTRITO");
        lblLimiteCheques3.setAlignmentX(0.5F);
        lblLimiteCheques3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDistrict.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtDistrict.setForeground(new java.awt.Color(204, 204, 204));
        txtDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistrictActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteCheques3Layout = new javax.swing.GroupLayout(panLimiteCheques3);
        panLimiteCheques3.setLayout(panLimiteCheques3Layout);
        panLimiteCheques3Layout.setHorizontalGroup(
            panLimiteCheques3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteCheques3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDistrict, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteCheques3Layout.setVerticalGroup(
            panLimiteCheques3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteCheques3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteCheques3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteCheques3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 300, 40));

        lblLimiteCheques4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques4.setText("DIRECCION");
        lblLimiteCheques4.setAlignmentX(0.5F);
        lblLimiteCheques4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtAdress.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtAdress.setForeground(new java.awt.Color(204, 204, 204));
        txtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteCheques4Layout = new javax.swing.GroupLayout(panLimiteCheques4);
        panLimiteCheques4.setLayout(panLimiteCheques4Layout);
        panLimiteCheques4Layout.setHorizontalGroup(
            panLimiteCheques4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteCheques4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques4)
                .addContainerGap(814, Short.MAX_VALUE))
            .addGroup(panLimiteCheques4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panLimiteCheques4Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(txtAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panLimiteCheques4Layout.setVerticalGroup(
            panLimiteCheques4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteCheques4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panLimiteCheques4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panLimiteCheques4Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        jPanel1.add(panLimiteCheques4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 920, 40));

        lblLimiteCheques5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques5.setText("TELEFONO");
        lblLimiteCheques5.setAlignmentX(0.5F);
        lblLimiteCheques5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPhoneNumber.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteCheques5Layout = new javax.swing.GroupLayout(panLimiteCheques5);
        panLimiteCheques5.setLayout(panLimiteCheques5Layout);
        panLimiteCheques5Layout.setHorizontalGroup(
            panLimiteCheques5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteCheques5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteCheques5Layout.setVerticalGroup(
            panLimiteCheques5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteCheques5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteCheques5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteCheques5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 450, 40));

        lblLimiteCheques6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblLimiteCheques6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimiteCheques6.setText("CORREO ELECTRONICO");
        lblLimiteCheques6.setAlignmentX(0.5F);
        lblLimiteCheques6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLimiteCheques6Layout = new javax.swing.GroupLayout(panLimiteCheques6);
        panLimiteCheques6.setLayout(panLimiteCheques6Layout);
        panLimiteCheques6Layout.setHorizontalGroup(
            panLimiteCheques6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLimiteCheques6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimiteCheques6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLimiteCheques6Layout.setVerticalGroup(
            panLimiteCheques6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLimiteCheques6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLimiteCheques6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteCheques6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panLimiteCheques6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 460, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtComisionPorChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComisionPorChequeActionPerformed
    }//GEN-LAST:event_txtComisionPorChequeActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
	String name = txtName.getText();
	String surname= txtSurname.getText();
	String idString= txtDocID.getText();
	String idType= txtDocType.getText();
	String year= txtBirthYear.getText();
	String month= txtBirthMonth.getText();
	String day= txtBirthDay.getText();
	String region= txtRegion.getText();
	String district= txtDistrict.getText();
	String province= txtProvince.getText();
	String adress= txtAdress.getText();
	String phoneNumber= txtPhoneNumber.getText();
	String email= txtEmail.getText();
	String civilStatus= txtCivilStatus.getText();
	boolean status = false;
	try {
		status = comp.createNatural(name, surname, idString, idType, year, month, day, region, district, province, adress, phoneNumber, email, civilStatus);
	} catch (InvalidInput e) {
		
	}
	if (status){
		JOptionPane.showMessageDialog(this, "Operacion exitosa", "Datos guardados", JOptionPane.INFORMATION_MESSAGE);
		jbtGuardar.setBackground(new Color(51, 51, 255));
	}
	else{
		JOptionPane.showMessageDialog(this, "Datos invalidos", "Error en la operacion", JOptionPane.ERROR_MESSAGE);
		jbtGuardar.setBackground(new Color(255, 51, 51));
	}	
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameActionPerformed

    private void txtDocIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocIDActionPerformed

    private void txtDocTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocTypeActionPerformed

    private void txtCivilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCivilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCivilStatusActionPerformed

    private void txtBirthYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthYearActionPerformed

    private void txtBirthMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthMonthActionPerformed

    private void txtProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvinceActionPerformed

    private void txtBirthDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDayActionPerformed

    private void txtRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionActionPerformed

    private void txtDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistrictActionPerformed

    private void txtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdressActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JLabel lblComisionPorCheque;
    private javax.swing.JLabel lblInteresAplicado;
    private javax.swing.JLabel lblInteresAplicado1;
    private javax.swing.JLabel lblLimiteCheques;
    private javax.swing.JLabel lblLimiteCheques1;
    private javax.swing.JLabel lblLimiteCheques2;
    private javax.swing.JLabel lblLimiteCheques3;
    private javax.swing.JLabel lblLimiteCheques4;
    private javax.swing.JLabel lblLimiteCheques5;
    private javax.swing.JLabel lblLimiteCheques6;
    private javax.swing.JLabel lblLimiteSobregiro;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JLabel lblTipoMoneda;
    private javax.swing.JLabel lblTitularDeLaCuenta;
    private javax.swing.JPanel panComisionPorCheque;
    private javax.swing.JPanel panInteresAplicado;
    private javax.swing.JPanel panInteresAplicado1;
    private javax.swing.JPanel panLimiteCheques;
    private javax.swing.JPanel panLimiteCheques1;
    private javax.swing.JPanel panLimiteCheques2;
    private javax.swing.JPanel panLimiteCheques3;
    private javax.swing.JPanel panLimiteCheques4;
    private javax.swing.JPanel panLimiteCheques5;
    private javax.swing.JPanel panLimiteCheques6;
    private javax.swing.JPanel panLimiteSobregiro;
    private javax.swing.JPanel panSaldoInicial;
    private javax.swing.JPanel panTipoMoneda;
    private javax.swing.JPanel panTitularDeLaCuenta;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtBirthDay;
    private javax.swing.JTextField txtBirthMonth;
    private javax.swing.JTextField txtBirthYear;
    private javax.swing.JTextField txtCivilStatus;
    private javax.swing.JTextField txtComisionPorCheque;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtDocID;
    private javax.swing.JTextField txtDocType;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtProvince;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
