/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

/**
 *
 * @author jhose
 */
public class PanCrearCuentaCorriente extends javax.swing.JPanel {

    /**
     * Creates new form PanCrearCuentaCorriente
     */
    public PanCrearCuentaCorriente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        txtTipoMoneda = new javax.swing.JTextField();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtFechaApertura = new javax.swing.JTextField();
        TxtTitularCuenta = new javax.swing.JTextField();
        txtInteresAplicado = new javax.swing.JTextField();
        txtLimiteSobregiros = new javax.swing.JTextField();
        txtEmisionCheques = new javax.swing.JTextField();
        txtNumerosCheques = new javax.swing.JTextField();
        txtSaldoInicial = new javax.swing.JTextField();
        txtIngresoFechaApertura = new javax.swing.JTextField();
        txtIngresoSaldoInicial = new javax.swing.JTextField();
        txtIngresoTipoMoneda = new javax.swing.JTextField();
        txtIngresoTitularCuenta = new javax.swing.JTextField();
        txtIngresoInteresAplicado = new javax.swing.JTextField();
        txtIngresoLimiteSobregiros = new javax.swing.JTextField();
        txtIngresoLimiteCheques = new javax.swing.JTextField();
        txtIngresoNumeroCheques = new javax.swing.JTextField();
        txtIngresoNumeroCuenta = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtComisionCheques = new javax.swing.JTextField();
        txtIngresoComisionCheques = new javax.swing.JTextField();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1136, 576));
        //panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipoMoneda.setBackground(new java.awt.Color(0, 102, 255));
        txtTipoMoneda.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtTipoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoMoneda.setText("Tipo de moneda");
        txtTipoMoneda.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtTipoMoneda);

        txtNumeroCuenta.setBackground(new java.awt.Color(0, 102, 255));
        txtNumeroCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtNumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroCuenta.setText("Numero de cuenta");
        txtNumeroCuenta.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtNumeroCuenta);

        txtFechaApertura.setBackground(new java.awt.Color(0, 102, 255));
        txtFechaApertura.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtFechaApertura.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaApertura.setText("Fecha de apertura");
        txtFechaApertura.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtFechaApertura);

        TxtTitularCuenta.setBackground(new java.awt.Color(0, 102, 255));
        TxtTitularCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        TxtTitularCuenta.setForeground(new java.awt.Color(255, 255, 255));
        TxtTitularCuenta.setText("Titular de la cuenta");
        TxtTitularCuenta.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(TxtTitularCuenta);

        txtInteresAplicado.setBackground(new java.awt.Color(0, 102, 255));
        txtInteresAplicado.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtInteresAplicado.setForeground(new java.awt.Color(255, 255, 255));
        txtInteresAplicado.setText("Interes aplicado");
        txtInteresAplicado.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtInteresAplicado);

        txtLimiteSobregiros.setBackground(new java.awt.Color(0, 102, 255));
        txtLimiteSobregiros.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtLimiteSobregiros.setForeground(new java.awt.Color(255, 255, 255));
        txtLimiteSobregiros.setText("Limite de sobregiros");
        txtLimiteSobregiros.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtLimiteSobregiros);

        txtEmisionCheques.setBackground(new java.awt.Color(0, 102, 255));
        txtEmisionCheques.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtEmisionCheques.setForeground(new java.awt.Color(255, 255, 255));
        txtEmisionCheques.setText("Limite de cheques");
        txtEmisionCheques.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtEmisionCheques);

        txtNumerosCheques.setBackground(new java.awt.Color(0, 102, 255));
        txtNumerosCheques.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtNumerosCheques.setForeground(new java.awt.Color(255, 255, 255));
        txtNumerosCheques.setText("Numero de cheques");
        txtNumerosCheques.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtNumerosCheques);

        txtSaldoInicial.setBackground(new java.awt.Color(0, 102, 255));
        txtSaldoInicial.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtSaldoInicial.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldoInicial.setText("Saldo inicial");
        txtSaldoInicial.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtSaldoInicial);

        txtIngresoFechaApertura.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoFechaApertura.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoFechaApertura);

        txtIngresoSaldoInicial.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoSaldoInicial.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoSaldoInicial);

        txtIngresoTipoMoneda.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoTipoMoneda.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoTipoMoneda);

        txtIngresoTitularCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoTitularCuenta.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoTitularCuenta);

        txtIngresoInteresAplicado.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoInteresAplicado.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoInteresAplicado);

        txtIngresoLimiteSobregiros.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoLimiteSobregiros.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoLimiteSobregiros);

        txtIngresoLimiteCheques.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoLimiteCheques.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoLimiteCheques);

        txtIngresoNumeroCheques.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoNumeroCheques.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoNumeroCheques);

        txtIngresoNumeroCuenta.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoNumeroCuenta.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoNumeroCuenta);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_file.gif"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panBlanco.add(btnGuardar);

        txtComisionCheques.setBackground(new java.awt.Color(0, 102, 255));
        txtComisionCheques.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtComisionCheques.setForeground(new java.awt.Color(255, 255, 255));
        txtComisionCheques.setText("Comision por cheques");
        txtComisionCheques.setPreferredSize(new java.awt.Dimension(210, 44));
        panBlanco.add(txtComisionCheques);

        txtIngresoComisionCheques.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        txtIngresoComisionCheques.setPreferredSize(new java.awt.Dimension(300, 44));
        panBlanco.add(txtIngresoComisionCheques);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTitularCuenta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JTextField txtComisionCheques;
    private javax.swing.JTextField txtEmisionCheques;
    private javax.swing.JTextField txtFechaApertura;
    private javax.swing.JTextField txtIngresoComisionCheques;
    private javax.swing.JTextField txtIngresoFechaApertura;
    private javax.swing.JTextField txtIngresoInteresAplicado;
    private javax.swing.JTextField txtIngresoLimiteCheques;
    private javax.swing.JTextField txtIngresoLimiteSobregiros;
    private javax.swing.JTextField txtIngresoNumeroCheques;
    private javax.swing.JTextField txtIngresoNumeroCuenta;
    private javax.swing.JTextField txtIngresoSaldoInicial;
    private javax.swing.JTextField txtIngresoTipoMoneda;
    private javax.swing.JTextField txtIngresoTitularCuenta;
    private javax.swing.JTextField txtInteresAplicado;
    private javax.swing.JTextField txtLimiteSobregiros;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumerosCheques;
    private javax.swing.JTextField txtSaldoInicial;
    private javax.swing.JTextField txtTipoMoneda;
    // End of variables declaration//GEN-END:variables
}
