/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import java.awt.Color;

import common.exceptions.ClientNotFound;
import common.exceptions.InvalidInput;
import components.Employee;
import objects.accounts.Persona;

/**
 *
 * @author edu11
 */
public class PanRegistrarTransferencia extends javax.swing.JPanel {

    /**
     * Creates new form PanCrearCuentaAhorro2
     */
	private Employee comp;
	private boolean populated = false;
    public PanRegistrarTransferencia(Employee comp) {
		this.comp = comp;
        initComponents();
		cmbListaCuentasDestino.removeAllItems();
		for(String i: comp.getListaNrosCuenta()){
			cmbListaCuentasDestino.addItem(i);
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuentaOrigen = new javax.swing.JLabel();
        cmbListaCuentasDestino = new javax.swing.JComboBox<>();
        lblCuentaDestinatario = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        lblConcepto = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        lblCuentaDestinatario1 = new javax.swing.JLabel();
        btnTransferir1 = new javax.swing.JButton();
        txtDocClient = new javax.swing.JTextField();
        cmbListaCuentasOrigen = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1120, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuentaOrigen.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCuentaOrigen.setText("Cuenta Origen:");
        jPanel1.add(lblCuentaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        cmbListaCuentasDestino.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cmbListaCuentasDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbListaCuentasDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 380, 40));

        lblCuentaDestinatario.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCuentaDestinatario.setText("Documento del cliente");
        jPanel1.add(lblCuentaDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblImporte.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblImporte.setText("Importe:");
        jPanel1.add(lblImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        txtImporte.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });
        jPanel1.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 380, 40));

        lblConcepto.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblConcepto.setText("Concepto:");
        jPanel1.add(lblConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        txtConcepto.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConceptoActionPerformed(evt);
            }
        });
        jPanel1.add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 380, 40));

        btnTransferir.setBackground(new java.awt.Color(51, 51, 255));
        btnTransferir.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir.setText("Actualizar");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, 30));

        lblCuentaDestinatario1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCuentaDestinatario1.setText("Cuenta del destinatario: ");
        jPanel1.add(lblCuentaDestinatario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        btnTransferir1.setBackground(new java.awt.Color(51, 51, 255));
        btnTransferir1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnTransferir1.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir1.setText("Transferir");
        btnTransferir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransferir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 130, 30));

        txtDocClient.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtDocClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocClientActionPerformed(evt);
            }
        });
        jPanel1.add(txtDocClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 380, 40));

        cmbListaCuentasOrigen.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cmbListaCuentasOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbListaCuentasOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteActionPerformed

    private void txtConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConceptoActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnTransferir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferir1ActionPerformed

    private void txtDocClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnTransferir1;
    private javax.swing.JComboBox<String> cmbListaCuentasDestino;
    private javax.swing.JComboBox<String> cmbListaCuentasOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblCuentaDestinatario;
    private javax.swing.JLabel lblCuentaDestinatario1;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtDocClient;
    private javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
