/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import common.exceptions.AccountNotFound;
import common.exceptions.BadStringToParse;
import common.exceptions.InvalidInput;
import components.Employee;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author edu11
 */
public class PanRegistrarRetiro extends javax.swing.JPanel {

    /**
     * Creates new form PanCrearCuentaAhorro2
     */
	private Employee comp;
	private boolean populated = false;
    public PanRegistrarRetiro(Employee comp) {
		this.comp = comp;
        initComponents();
        cmbListaCuentasOrigen.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuentaOrigen = new javax.swing.JLabel();
        lblCuentaDestinatario = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnPopularDatos = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        txtDocClient = new javax.swing.JTextField();
        cmbListaCuentasOrigen = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1120, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuentaOrigen.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCuentaOrigen.setText("Cuenta Origen:");
        jPanel1.add(lblCuentaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        lblCuentaDestinatario.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCuentaDestinatario.setText("Documento del cliente");
        jPanel1.add(lblCuentaDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblImporte.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblImporte.setText("Importe:");
        jPanel1.add(lblImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        txtImporte.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });
        jPanel1.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 380, 40));

        btnPopularDatos.setBackground(new java.awt.Color(51, 51, 255));
        btnPopularDatos.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnPopularDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnPopularDatos.setText("Actualizar");
        btnPopularDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopularDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPopularDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, 30));

        btnRetirar.setBackground(new java.awt.Color(51, 51, 255));
        btnRetirar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 130, 30));

        txtDocClient.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtDocClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocClientActionPerformed(evt);
            }
        });
        jPanel1.add(txtDocClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 380, 40));

        cmbListaCuentasOrigen.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cmbListaCuentasOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbListaCuentasOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
		btnRetirar.setBackground(new Color(51,51,255));
        String docString = txtDocClient.getText();
		
		float amount;
		try {
			amount = Float.parseFloat(txtImporte.getText());
		}
		catch(Exception e){
			amount = 0.0f;
		}
        try {
			if (!populated){
				throw new InvalidInput();
			}
			boolean success = comp.doWithdraw(amount, (String)cmbListaCuentasOrigen.getSelectedItem(), docString);
			if (!success){
				btnRetirar.setBackground(new Color(255,51,51));
				JOptionPane.showMessageDialog(this, "Datos invalidos", "Error en la operacion", JOptionPane.ERROR_MESSAGE);

			}
			else {
			JOptionPane.showMessageDialog(this, "Operacion exitosa", "Datos guardados", JOptionPane.INFORMATION_MESSAGE);

			}
		} catch (AccountNotFound |  InvalidInput e) {
			JOptionPane.showMessageDialog(this, "Datos invalidos", "Error en la operacion", JOptionPane.ERROR_MESSAGE);
			btnRetirar.setBackground(new Color(255,51,51));
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnPopularDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopularDatosActionPerformed
        populated = true;
        cmbListaCuentasOrigen.removeAllItems();
        String docString = txtDocClient.getText();
        for(String i : comp.getListaNrosCuenta()){
            try {
                if (comp.searchCuenta(i).getId().equals(docString)){
                    cmbListaCuentasOrigen.addItem(i);
                }
            } catch (AccountNotFound | BadStringToParse e) {
                populated= false;
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPopularDatosActionPerformed

    private void txtDocClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPopularDatos;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JComboBox<String> cmbListaCuentasOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuentaDestinatario;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JTextField txtDocClient;
    private javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
