/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesEmpleado;

import java.awt.BorderLayout;
import javax.swing.ButtonGroup;

import components.Employee;
/**
 *
 * @author jhose
 */
public class PanRegistrarOperacion extends javax.swing.JPanel {

    private final javax.swing.ButtonGroup buttonGroupOpciones;
    
    /**
     * Creates new form PamCrearUsuario
     */

	private Employee comp;
    public PanRegistrarOperacion(Employee comp) {
		this.comp = comp;
        initComponents();
        buttonGroupOpciones = new ButtonGroup();
        buttonGroupOpciones.add(jrbCuentaAhorro);
        buttonGroupOpciones.add(jrbCuentaCorriente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        jrbCuentaAhorro = new javax.swing.JRadioButton();
        jrbCuentaCorriente = new javax.swing.JRadioButton();
        panContenido = new javax.swing.JPanel();
        jrbCuentaCorriente1 = new javax.swing.JRadioButton();
        jrbCuentaCorriente2 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(1284, 784));

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbCuentaAhorro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbCuentaAhorro.setForeground(new java.awt.Color(0, 51, 255));
        jrbCuentaAhorro.setText("Transferencia");
        jrbCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCuentaAhorroActionPerformed(evt);
            }
        });
        panBlanco.add(jrbCuentaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jrbCuentaCorriente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbCuentaCorriente.setForeground(new java.awt.Color(0, 51, 255));
        jrbCuentaCorriente.setText("Cheque");
        jrbCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCuentaCorrienteActionPerformed(evt);
            }
        });
        panBlanco.add(jrbCuentaCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        panContenido.setBackground(new java.awt.Color(204, 204, 204));
        panContenido.setPreferredSize(new java.awt.Dimension(1120, 680));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 760));
        panContenido.getAccessibleContext().setAccessibleName("");

        jrbCuentaCorriente1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbCuentaCorriente1.setForeground(new java.awt.Color(0, 51, 255));
        jrbCuentaCorriente1.setText("Deposito");
        jrbCuentaCorriente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCuentaCorriente1ActionPerformed(evt);
            }
        });
        panBlanco.add(jrbCuentaCorriente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jrbCuentaCorriente2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jrbCuentaCorriente2.setForeground(new java.awt.Color(0, 51, 255));
        jrbCuentaCorriente2.setText("Retiro");
        jrbCuentaCorriente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCuentaCorriente2ActionPerformed(evt);
            }
        });
        panBlanco.add(jrbCuentaCorriente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCuentaCorrienteActionPerformed
        PanCrearCuentaCorriente panCrearCuentaCorriente = new PanCrearCuentaCorriente(comp);
        panCrearCuentaCorriente.setSize(1100,670);
        panCrearCuentaCorriente.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(panCrearCuentaCorriente,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbCuentaCorrienteActionPerformed

    private void jrbCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCuentaAhorroActionPerformed
		PanCrearCuentaAhorro panCrearCuentaAhorro = new PanCrearCuentaAhorro(comp);
        panCrearCuentaAhorro.setSize(1100,670);
        panCrearCuentaAhorro.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(panCrearCuentaAhorro,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbCuentaAhorroActionPerformed

    private void jrbCuentaCorriente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCuentaCorriente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCuentaCorriente1ActionPerformed

    private void jrbCuentaCorriente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCuentaCorriente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCuentaCorriente2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jrbCuentaAhorro;
    private javax.swing.JRadioButton jrbCuentaCorriente;
    private javax.swing.JRadioButton jrbCuentaCorriente1;
    private javax.swing.JRadioButton jrbCuentaCorriente2;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    // End of variables declaration//GEN-END:variables
}
