/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesUsuario;

/**
 *
 * @author jhose
 */
public class PanConsultarSaldo extends javax.swing.JPanel {

    /**
     * Creates new form PanConsultarSaldo
     */
    public PanConsultarSaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        lblImporteRetiro = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtImporteRetirar = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImporteRetiro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblImporteRetiro.setForeground(new java.awt.Color(51, 51, 255));
        lblImporteRetiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporteRetiro.setText("Numero de Cuenta");
        panBlanco.add(lblImporteRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, -1));

        lblcontraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(51, 51, 255));
        lblcontraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcontraseña.setText("Nombre del Titular");
        panBlanco.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, -1));
        panBlanco.add(txtImporteRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 420, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        panBlanco.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 420, -1));

        btnRetirar.setBackground(new java.awt.Color(51, 51, 255));
        btnRetirar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.gif"))); // NOI18N
        btnRetirar.setText("Consultar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        panBlanco.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
 
            // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel lblImporteRetiro;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtImporteRetirar;
    // End of variables declaration//GEN-END:variables
}
