/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Presentacion.OperacionesUsuario;

import Presentacion.Principal.FrmVentanaPrincipalUsuario;
import java.awt.BorderLayout;
import javax.swing.ButtonGroup;

/**
 *
 * @author jhose
 */

public class PanOpciones extends javax.swing.JPanel {

    public PanOpciones() {
        initComponents();
        ButtonGroup buttonGroupOpciones = new javax.swing.ButtonGroup();
        buttonGroupOpciones.add(jrbVerResumen);
        buttonGroupOpciones.add(jrbRealizarTransferencia);
        buttonGroupOpciones.add(jrbEditarInformacion);
    }

    private void cargarPanel(javax.swing.JPanel panel) {
    panel.setSize(1100, 576);
    panel.setLocation(0, 0);

    panContenido.removeAll();
    panContenido.add(panel, BorderLayout.CENTER);
    panContenido.revalidate();
    panContenido.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        lblOpciones = new javax.swing.JLabel();
        jrbRealizarTransferencia = new javax.swing.JRadioButton();
        jrbEditarInformacion = new javax.swing.JRadioButton();
        jrbVerResumen = new javax.swing.JRadioButton();
        panContenido = new javax.swing.JPanel();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setMaximumSize(new java.awt.Dimension(1440, 960));
        panBlanco.setPreferredSize(new java.awt.Dimension(1440, 960));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpciones.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(51, 51, 255));
        lblOpciones.setText("Opciones");
        panBlanco.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jrbRealizarTransferencia.setBackground(new java.awt.Color(51, 51, 255));
        jrbRealizarTransferencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jrbRealizarTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        jrbRealizarTransferencia.setText("Realizar transferencia");
        jrbRealizarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRealizarTransferenciaActionPerformed(evt);
            }
        });
        panBlanco.add(jrbRealizarTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, -1));

        jrbEditarInformacion.setBackground(new java.awt.Color(51, 51, 255));
        jrbEditarInformacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jrbEditarInformacion.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditarInformacion.setText("Editar informacion");
        jrbEditarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEditarInformacionActionPerformed(evt);
            }
        });
        panBlanco.add(jrbEditarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, -1));

        jrbVerResumen.setBackground(new java.awt.Color(51, 51, 255));
        jrbVerResumen.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jrbVerResumen.setForeground(new java.awt.Color(255, 255, 255));
        jrbVerResumen.setText("Ver resumen");
        jrbVerResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVerResumenActionPerformed(evt);
            }
        });
        panBlanco.add(jrbVerResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 160, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));
        panContenido.setPreferredSize(new java.awt.Dimension(1100, 576));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbVerResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVerResumenActionPerformed
        cargarPanel(new PanVerResumen());
    }//GEN-LAST:event_jrbVerResumenActionPerformed

    private void jrbRealizarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRealizarTransferenciaActionPerformed
        cargarPanel(new PanRealizarTranferencia());
    }//GEN-LAST:event_jrbRealizarTransferenciaActionPerformed

    private void jrbEditarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEditarInformacionActionPerformed
        cargarPanel(new PanEditarInformacion());
    }//GEN-LAST:event_jrbEditarInformacionActionPerformed
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jrbEditarInformacion;
    private javax.swing.JRadioButton jrbRealizarTransferencia;
    private javax.swing.JRadioButton jrbVerResumen;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    // End of variables declaration//GEN-END:variables
}