/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.OperacionesUsuario;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author jhose
 */
    
public class PanVerResumen extends javax.swing.JPanel {
    
   public PanVerResumen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                         
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        btnDescargarResumen = new javax.swing.JButton();
        lblDescargarResumen = new javax.swing.JLabel();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDescargarResumen.setBackground(new java.awt.Color(51, 51, 255));
        btnDescargarResumen.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDescargarResumen.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargarResumen.setText("Descargar");
        btnDescargarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarResumenActionPerformed(evt);
            }
        });
        panBlanco.add(btnDescargarResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 560, 370));

        lblDescargarResumen.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblDescargarResumen.setForeground(new java.awt.Color(51, 51, 255));
        lblDescargarResumen.setText("Descargar resumen");
        panBlanco.add(lblDescargarResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescargarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarResumenActionPerformed
        
        String nombreCliente = "Juan";
        String apellidoCliente = "Pérez";
        String dniCliente = "12345678";
        double saldo = 5000.50;
        String tipoCuenta = "Ahorro";
        String fechaDescarga = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        // Creamos el nombre del archivo
        String nombreArchivo = "Resumen_" + nombreCliente + "_" + apellidoCliente + ".txt";

        // Formateamos el contenido que se escribirá en el archivo
        String contenido = String.format("""
                Nombre: %s
                Apellidos: %s
                DNI: %s
                Saldo: %.2f
                Tipo de cuenta: %s
                Fecha de descarga: %s
                """, nombreCliente, apellidoCliente, dniCliente, saldo, tipoCuenta, fechaDescarga);

        // Intentamos guardar el archivo
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo))) {
            writer.write(contenido);  // Escribimos el contenido en el archivo
            // Mostramos un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Archivo descargado con éxito: " + nombreArchivo,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            // En caso de error, mostramos un mensaje de error
            JOptionPane.showMessageDialog(this, "Error al descargar el archivo: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDescargarResumenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarResumen;
    private javax.swing.JLabel lblDescargarResumen;
    private javax.swing.JPanel panBlanco;
    // End of variables declaration//GEN-END:variables
}
