package gui;

public class IfrmEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmEmpleado
     */
    public IfrmEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCrearCuenta = new javax.swing.JMenu();
        mnuCuentaAhorros = new javax.swing.JMenuItem();
        mnuCuentaCorriente = new javax.swing.JMenuItem();
        mnuCrearCliente = new javax.swing.JMenu();
        mniNatural = new javax.swing.JMenuItem();
        mniJuridico = new javax.swing.JMenuItem();
        mnuMovimiento = new javax.swing.JMenu();
        mniDeposito = new javax.swing.JMenuItem();
        mniRetiro = new javax.swing.JMenuItem();
        mniDepositarCheque = new javax.swing.JMenuItem();
        mniTransferencia = new javax.swing.JMenuItem();
        mniEmitirChequera = new javax.swing.JMenuItem();
        mnuActualizarInformacion = new javax.swing.JMenu();
        mnuSalir2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar4.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar4.add(jMenu2);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        mnuCrearCuenta.setText("Crear Cuenta");

        mnuCuentaAhorros.setText("Cuenta Ahorros");
        mnuCuentaAhorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCuentaAhorrosActionPerformed(evt);
            }
        });
        mnuCrearCuenta.add(mnuCuentaAhorros);

        mnuCuentaCorriente.setText("Cuenta Corriente");
        mnuCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCuentaCorrienteActionPerformed(evt);
            }
        });
        mnuCrearCuenta.add(mnuCuentaCorriente);

        jMenuBar1.add(mnuCrearCuenta);

        mnuCrearCliente.setText("Crear Cliente");

        mniNatural.setText("Natural");
        mnuCrearCliente.add(mniNatural);

        mniJuridico.setText("Juridico");
        mniJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniJuridicoActionPerformed(evt);
            }
        });
        mnuCrearCliente.add(mniJuridico);

        jMenuBar1.add(mnuCrearCliente);

        mnuMovimiento.setText("Movimiento");

        mniDeposito.setText("Deposito");
        mnuMovimiento.add(mniDeposito);

        mniRetiro.setText("Retiro");
        mnuMovimiento.add(mniRetiro);

        mniDepositarCheque.setText("Depositar Cheque");
        mniDepositarCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDepositarChequeActionPerformed(evt);
            }
        });
        mnuMovimiento.add(mniDepositarCheque);

        mniTransferencia.setText("Transferencia");
        mnuMovimiento.add(mniTransferencia);

        mniEmitirChequera.setText("Emitir Chequera");
        mnuMovimiento.add(mniEmitirChequera);

        jMenuBar1.add(mnuMovimiento);

        mnuActualizarInformacion.setText("Actualizar Informacion");
        jMenuBar1.add(mnuActualizarInformacion);

        mnuSalir2.setText("Salir");
        jMenuBar1.add(mnuSalir2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void mnuCuentaAhorrosActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void mnuCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void mniJuridicoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void mniDepositarChequeActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  


    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mniDepositarCheque;
    private javax.swing.JMenuItem mniDeposito;
    private javax.swing.JMenuItem mniEmitirChequera;
    private javax.swing.JMenuItem mniJuridico;
    private javax.swing.JMenuItem mniNatural;
    private javax.swing.JMenuItem mniRetiro;
    private javax.swing.JMenuItem mniTransferencia;
    private javax.swing.JMenu mnuActualizarInformacion;
    private javax.swing.JMenu mnuCrearCliente;
    private javax.swing.JMenu mnuCrearCuenta;
    private javax.swing.JMenuItem mnuCuentaAhorros;
    private javax.swing.JMenuItem mnuCuentaCorriente;
    private javax.swing.JMenu mnuMovimiento;
    private javax.swing.JMenu mnuSalir2;
    // End of variables declaration                   
}
