package gui;

public class IfrmAdministrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmAdministrador
     */
    public IfrmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVerLogs = new javax.swing.JMenu();
        mnuVerCuentas = new javax.swing.JMenu();
        mnuActividad = new javax.swing.JMenuItem();
        mnuBalance = new javax.swing.JMenuItem();
        mnuPropietario = new javax.swing.JMenuItem();
        mnuResumenActividad = new javax.swing.JMenu();
        mnuPorDia = new javax.swing.JMenuItem();
        mnuPorMes = new javax.swing.JMenuItem();
        mniPorAnyo = new javax.swing.JMenuItem();
        mniTotal = new javax.swing.JMenuItem();
        mnuSalir1 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        mnuVerLogs.setText("Ver Logs");
        jMenuBar1.add(mnuVerLogs);

        mnuVerCuentas.setText("Ver Cuentas");
        mnuVerCuentas.setToolTipText("");

        mnuActividad.setText("Actividad");
        mnuVerCuentas.add(mnuActividad);

        mnuBalance.setText("Balance");
        mnuBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBalanceActionPerformed(evt);
            }
        });
        mnuVerCuentas.add(mnuBalance);

        mnuPropietario.setText("Propietario");
        mnuVerCuentas.add(mnuPropietario);

        jMenuBar1.add(mnuVerCuentas);

        mnuResumenActividad.setText("Resumen de Actividad");

        mnuPorDia.setText("Por dia");
        mnuResumenActividad.add(mnuPorDia);

        mnuPorMes.setText("Por mes");
        mnuResumenActividad.add(mnuPorMes);

        mniPorAnyo.setText("Por año");
        mnuResumenActividad.add(mniPorAnyo);

        mniTotal.setText("Total");
        mnuResumenActividad.add(mniTotal);

        jMenuBar1.add(mnuResumenActividad);

        mnuSalir1.setText("Salir");
        jMenuBar1.add(mnuSalir1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void mnuBalanceActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniPorAnyo;
    private javax.swing.JMenuItem mniTotal;
    private javax.swing.JMenuItem mnuActividad;
    private javax.swing.JMenuItem mnuBalance;
    private javax.swing.JMenuItem mnuPorDia;
    private javax.swing.JMenuItem mnuPorMes;
    private javax.swing.JMenuItem mnuPropietario;
    private javax.swing.JMenu mnuResumenActividad;
    private javax.swing.JMenu mnuSalir1;
    private javax.swing.JMenu mnuVerCuentas;
    private javax.swing.JMenu mnuVerLogs;
    // End of variables declaration                   
}
