/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.principal;

import java.awt.BorderLayout;

import gui.operacionesEmpleado.PamActividadCuenta;
import gui.operacionesEmpleado.PamCrearUsuario;
import gui.operacionesEmpleado.PamInformacionCuenta;
import gui.operacionesEmpleado.PamMovimientos;
import gui.operacionesEmpleado.PamTransferencias;
import gui.operacionesEmpleado.PamUsuarios;

/**
 *
 * @author jhose
 */
public class FrmVentanaPrincipalEmpleado extends javax.swing.JFrame {
    
    private final javax.swing.ButtonGroup buttonGroupOpciones;
    /**
     * Creates new form FrmVentanaPrincipalEmpleado
     */
    public FrmVentanaPrincipalEmpleado() {
        initComponents();
        buttonGroupOpciones = new javax.swing.ButtonGroup();
        buttonGroupOpciones.add(jrbCrearUsuario);
        buttonGroupOpciones.add(jrbInformacionCuenta);
        buttonGroupOpciones.add(jrbTransferencias);
        buttonGroupOpciones.add(jrbMovimientos);
        buttonGroupOpciones.add(jrbUsuarios);
        buttonGroupOpciones.add(jrbActividadCuenta);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        panOpciones = new javax.swing.JPanel();
        lblEmpleado = new javax.swing.JLabel();
        jrbInformacionCuenta = new javax.swing.JRadioButton();
        jrbCrearUsuario = new javax.swing.JRadioButton();
        jrbTransferencias = new javax.swing.JRadioButton();
        jrbMovimientos = new javax.swing.JRadioButton();
        jrbUsuarios = new javax.swing.JRadioButton();
        jrbActividadCuenta = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setMinimumSize(new java.awt.Dimension(1127, 960));
        panBlanco.setPreferredSize(new java.awt.Dimension(1440, 960));
        //panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panOpciones.setBackground(new java.awt.Color(255, 255, 255));
        panOpciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panOpciones.setPreferredSize(new java.awt.Dimension(300, 960));

        lblEmpleado.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(0, 51, 255));
        lblEmpleado.setText("Menu");

        jrbInformacionCuenta.setBackground(new java.awt.Color(0, 51, 255));
        jrbInformacionCuenta.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbInformacionCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jrbInformacionCuenta.setText("Informacion de cuenta");
        jrbInformacionCuenta.setToolTipText("");
        jrbInformacionCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbInformacionCuenta.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbInformacionCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInformacionCuentaActionPerformed(evt);
            }
        });

        jrbCrearUsuario.setBackground(new java.awt.Color(0, 51, 255));
        jrbCrearUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jrbCrearUsuario.setText("Crear cuenta");
        jrbCrearUsuario.setToolTipText("");
        jrbCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbCrearUsuario.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCrearUsuarioActionPerformed(evt);
            }
        });

        jrbTransferencias.setBackground(new java.awt.Color(0, 51, 255));
        jrbTransferencias.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbTransferencias.setForeground(new java.awt.Color(255, 255, 255));
        jrbTransferencias.setText("Transferencias");
        jrbTransferencias.setToolTipText("");
        jrbTransferencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbTransferencias.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTransferenciasActionPerformed(evt);
            }
        });

        jrbMovimientos.setBackground(new java.awt.Color(0, 51, 255));
        jrbMovimientos.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        jrbMovimientos.setText("Movimientos");
        jrbMovimientos.setToolTipText("");
        jrbMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbMovimientos.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMovimientosActionPerformed(evt);
            }
        });

        jrbUsuarios.setBackground(new java.awt.Color(0, 51, 255));
        jrbUsuarios.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jrbUsuarios.setText("Usuarios");
        jrbUsuarios.setToolTipText("");
        jrbUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbUsuarios.setPreferredSize(new java.awt.Dimension(200, 40));
        jrbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUsuariosActionPerformed(evt);
            }
        });

        jrbActividadCuenta.setBackground(new java.awt.Color(0, 51, 255));
        jrbActividadCuenta.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbActividadCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jrbActividadCuenta.setText("Actividad de cuenta");
        jrbActividadCuenta.setToolTipText("");
        jrbActividadCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbActividadCuenta.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbActividadCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbActividadCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOpcionesLayout = new javax.swing.GroupLayout(panOpciones);
        panOpciones.setLayout(panOpcionesLayout);
        panOpcionesLayout.setHorizontalGroup(
            panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpcionesLayout.createSequentialGroup()
                .addGroup(panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOpcionesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrbInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jrbCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jrbTransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jrbMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jrbUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbActividadCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(panOpcionesLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblEmpleado)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panOpcionesLayout.setVerticalGroup(
            panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpcionesLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblEmpleado)
                .addGap(70, 70, 70)
                .addComponent(jrbCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbInformacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbTransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbActividadCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        panBlanco.add(panOpciones);

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 51, 255));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panBlanco.add(btnSalir);

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jrbCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCrearUsuarioActionPerformed
        PamCrearUsuario pamCrearUsuario = new PamCrearUsuario();
        pamCrearUsuario.setSize(1140,784);
        pamCrearUsuario.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(pamCrearUsuario,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbCrearUsuarioActionPerformed

    private void jrbMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMovimientosActionPerformed
        PamMovimientos pamMovimientos = new PamMovimientos();
        pamMovimientos.setSize(1140,784);
        pamMovimientos.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(pamMovimientos,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbMovimientosActionPerformed

    private void jrbTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTransferenciasActionPerformed
        PamTransferencias pamTransferencias = new PamTransferencias();
        pamTransferencias.setSize(1140,784);
        pamTransferencias.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(pamTransferencias,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbTransferenciasActionPerformed

    private void jrbInformacionCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInformacionCuentaActionPerformed
        PamInformacionCuenta pamInformacionCuenta = new PamInformacionCuenta();
        pamInformacionCuenta.setSize(1140,784);
        pamInformacionCuenta.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(pamInformacionCuenta,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbInformacionCuentaActionPerformed

    private void jrbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUsuariosActionPerformed
    
        PamUsuarios pamUsuarios = new PamUsuarios();
        pamUsuarios.setSize(1140, 784);
        pamUsuarios.setLocation(0, 0);

        panContenido.removeAll();
        panContenido.add(pamUsuarios, BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbUsuariosActionPerformed

    private void jrbActividadCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbActividadCuentaActionPerformed
        PamActividadCuenta pamActividadCuenta = new PamActividadCuenta();
        pamActividadCuenta.setSize(1140,784);
        pamActividadCuenta.setLocation(0,0);

        panContenido.removeAll();
        panContenido.add(pamActividadCuenta,BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }//GEN-LAST:event_jrbActividadCuentaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       FrmOrquiBank returnOrquiBank = new FrmOrquiBank();
       returnOrquiBank.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmVentanaPrincipalEmpleado().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton jrbActividadCuenta;
    private javax.swing.JRadioButton jrbCrearUsuario;
    private javax.swing.JRadioButton jrbInformacionCuenta;
    private javax.swing.JRadioButton jrbMovimientos;
    private javax.swing.JRadioButton jrbTransferencias;
    private javax.swing.JRadioButton jrbUsuarios;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panOpciones;
    // End of variables declaration//GEN-END:variables
}
