/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.principal;

import components.Admin;
import java.awt.BorderLayout;

import gui.operacionesAdministrador.PanListaClientes;
import gui.operacionesAdministrador.PanListaCuentas;
import gui.operacionesAdministrador.PanLogs;

/**
 *
 * @author jhose
 */
public class FrmVentanaPrincipalAdministrador extends javax.swing.JFrame {

    private final javax.swing.ButtonGroup buttonGroupOpciones;
    private Admin adminComp = new Admin();

    /**
     * Creates new form FrmVentanaPrincipalAdministrador
     */
    public FrmVentanaPrincipalAdministrador() {
        initComponents();

        buttonGroupOpciones = new javax.swing.ButtonGroup();
        buttonGroupOpciones.add(jrbLogs);
        buttonGroupOpciones.add(jrbListaClientes);
        buttonGroupOpciones.add(jrbListaCuentas);
    }

    private void cargarPanel(javax.swing.JPanel panel) {
        panel.setSize(1100, 576);
        panel.setLocation(0, 0);

        panContenido.removeAll();
        panContenido.add(panel, BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        panOpciones = new javax.swing.JPanel();
        lblAdministrador = new javax.swing.JLabel();
        jrbLogs = new javax.swing.JRadioButton();
        jrbListaClientes = new javax.swing.JRadioButton();
        jrbListaCuentas = new javax.swing.JRadioButton();
        panContenido = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1440, 960));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panOpciones.setBackground(new java.awt.Color(255, 255, 255));
        panOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panOpciones.setPreferredSize(new java.awt.Dimension(300, 960));

        lblAdministrador.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblAdministrador.setForeground(new java.awt.Color(0, 51, 255));
        lblAdministrador.setText("Menu");

        jrbLogs.setBackground(new java.awt.Color(0, 51, 255));
        jrbLogs.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbLogs.setForeground(new java.awt.Color(255, 255, 255));
        jrbLogs.setToolTipText("");
        jrbLogs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbLogs.setLabel("Ver logs");
        jrbLogs.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLogsActionPerformed(evt);
            }
        });

        jrbListaClientes.setBackground(new java.awt.Color(0, 51, 255));
        jrbListaClientes.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbListaClientes.setForeground(new java.awt.Color(255, 255, 255));
        jrbListaClientes.setToolTipText("");
        jrbListaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbListaClientes.setLabel("Lista clientes");
        jrbListaClientes.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbListaClientesActionPerformed(evt);
            }
        });

        jrbListaCuentas.setBackground(new java.awt.Color(0, 51, 255));
        jrbListaCuentas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbListaCuentas.setForeground(new java.awt.Color(255, 255, 255));
        jrbListaCuentas.setText("Lista cuentas");
        jrbListaCuentas.setToolTipText("");
        jrbListaCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbListaCuentas.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbListaCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbListaCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOpcionesLayout = new javax.swing.GroupLayout(panOpciones);
        panOpciones.setLayout(panOpcionesLayout);
        panOpcionesLayout.setHorizontalGroup(
                panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                .addGroup(panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(lblAdministrador))
                                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jrbLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jrbListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jrbListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(55, Short.MAX_VALUE))
        );
        panOpcionesLayout.setVerticalGroup(
                panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lblAdministrador)
                                .addGap(57, 57, 57)
                                .addComponent(jrbListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbLogs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(632, Short.MAX_VALUE))
        );

        panBlanco.add(panOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 960));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));
        panContenido.setPreferredSize(new java.awt.Dimension(1140, 784));
        panContenido.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
                panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1140, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
                panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 784, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 51, 255));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panBlanco.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLogsActionPerformed
        cargarPanel(new PanLogs(adminComp));
    }//GEN-LAST:event_jrbLogsActionPerformed

    private void jrbListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbListaClientesActionPerformed
        cargarPanel(new PanListaClientes(adminComp));
    }//GEN-LAST:event_jrbListaClientesActionPerformed

    private void jrbListaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbListaCuentasActionPerformed
        cargarPanel(new PanListaCuentas(adminComp));
    }//GEN-LAST:event_jrbListaCuentasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmOrquiBank returnOrquiBank = new FrmOrquiBank();
        returnOrquiBank.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmVentanaPrincipalAdministrador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton jrbListaClientes;
    private javax.swing.JRadioButton jrbListaCuentas;
    private javax.swing.JRadioButton jrbLogs;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panOpciones;
    // End of variables declaration//GEN-END:variables
}
