/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.principal;

import java.awt.BorderLayout;

import components.Employee;
import gui.operacionesEmpleado.PamCrearPersona;
import gui.operacionesEmpleado.PamCrearUsuario;
import gui.operacionesEmpleado.PanListaCuentas;
import gui.operacionesEmpleado.PanRegistrarOperacion;

/**
 *
 * @author jhose
 */
public class FrmVentanaPrincipalEmpleado extends javax.swing.JFrame {

    private final javax.swing.ButtonGroup buttonGroupOpciones;
    /**
     * Creates new form FrmVentanaPrincipalEmpleado
     */

    private Employee comp = new Employee();

    public FrmVentanaPrincipalEmpleado() {
        initComponents();
        buttonGroupOpciones = new javax.swing.ButtonGroup();
        buttonGroupOpciones.add(jrbCrearCuentas);
        buttonGroupOpciones.add(jrbInformacionCuentas);
        buttonGroupOpciones.add(jrbCrearCliente);
        buttonGroupOpciones.add(jrbOperaciones);

    }

    private void cargarPanel(javax.swing.JPanel panel) {
        panel.setSize(1100, 576);
        panel.setLocation(0, 0);

        panContenido.removeAll();
        panContenido.add(panel, BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        panOpciones = new javax.swing.JPanel();
        lblEmpleado = new javax.swing.JLabel();
        jrbInformacionCuentas = new javax.swing.JRadioButton();
        jrbCrearCuentas = new javax.swing.JRadioButton();
        jrbCrearCliente = new javax.swing.JRadioButton();
        jrbOperaciones = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        panContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setMinimumSize(new java.awt.Dimension(1127, 960));
        panBlanco.setPreferredSize(new java.awt.Dimension(1440, 960));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panOpciones.setBackground(new java.awt.Color(255, 255, 255));
        panOpciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panOpciones.setPreferredSize(new java.awt.Dimension(300, 960));

        lblEmpleado.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(0, 51, 255));
        lblEmpleado.setText("Menu");

        jrbInformacionCuentas.setBackground(new java.awt.Color(0, 51, 255));
        jrbInformacionCuentas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbInformacionCuentas.setForeground(new java.awt.Color(255, 255, 255));
        jrbInformacionCuentas.setText("Informacion de cuentas");
        jrbInformacionCuentas.setToolTipText("");
        jrbInformacionCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbInformacionCuentas.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbInformacionCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInformacionCuentasActionPerformed(evt);
            }
        });

        jrbCrearCuentas.setBackground(new java.awt.Color(0, 51, 255));
        jrbCrearCuentas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbCrearCuentas.setForeground(new java.awt.Color(255, 255, 255));
        jrbCrearCuentas.setText("Crear cuenta");
        jrbCrearCuentas.setToolTipText("");
        jrbCrearCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbCrearCuentas.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbCrearCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCrearCuentasActionPerformed(evt);
            }
        });

        jrbCrearCliente.setBackground(new java.awt.Color(0, 51, 255));
        jrbCrearCliente.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbCrearCliente.setForeground(new java.awt.Color(255, 255, 255));
        jrbCrearCliente.setText("Crear cliente");
        jrbCrearCliente.setToolTipText("");
        jrbCrearCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbCrearCliente.setPreferredSize(new java.awt.Dimension(240, 40));
        jrbCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCrearClienteActionPerformed(evt);
            }
        });

        jrbOperaciones.setBackground(new java.awt.Color(0, 51, 255));
        jrbOperaciones.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jrbOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        jrbOperaciones.setText("Operaciones");
        jrbOperaciones.setToolTipText("");
        jrbOperaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbOperaciones.setPreferredSize(new java.awt.Dimension(200, 40));
        jrbOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOperacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOpcionesLayout = new javax.swing.GroupLayout(panOpciones);
        panOpciones.setLayout(panOpcionesLayout);
        panOpcionesLayout.setHorizontalGroup(
                panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                .addGroup(panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(lblEmpleado))
                                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addGroup(panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jrbInformacionCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(jrbCrearCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(jrbCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(jrbOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        panOpcionesLayout.setVerticalGroup(
                panOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panOpcionesLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblEmpleado)
                                .addGap(70, 70, 70)
                                .addComponent(jrbInformacionCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbCrearCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(529, Short.MAX_VALUE))
        );

        panBlanco.add(panOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 960));

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 51, 255));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panBlanco.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 90, -1, -1));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
                panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1140, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
                panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 870, Short.MAX_VALUE)
        );

        panBlanco.add(panContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 870));

        getContentPane().add(panBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCrearCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCrearCuentasActionPerformed
        cargarPanel(new PamCrearUsuario(comp));
    }//GEN-LAST:event_jrbCrearCuentasActionPerformed

    private void jrbCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCrearClienteActionPerformed
        cargarPanel(new PamCrearPersona(comp));
    }//GEN-LAST:event_jrbCrearClienteActionPerformed

    private void jrbInformacionCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInformacionCuentasActionPerformed
        cargarPanel(new PanListaCuentas(comp));
    }//GEN-LAST:event_jrbInformacionCuentasActionPerformed

    private void jrbOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOperacionesActionPerformed
        cargarPanel(new PanRegistrarOperacion(comp));
    }//GEN-LAST:event_jrbOperacionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmOrquiBank returnOrquiBank = new FrmOrquiBank();
        returnOrquiBank.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmVentanaPrincipalEmpleado().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton jrbCrearCliente;
    private javax.swing.JRadioButton jrbCrearCuentas;
    private javax.swing.JRadioButton jrbInformacionCuentas;
    private javax.swing.JRadioButton jrbOperaciones;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panOpciones;
    // End of variables declaration//GEN-END:variables
}
