/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesAdministrador;

import components.Admin;
import objects.accounts.Cuenta;

import javax.swing.table.DefaultTableModel;

import common.exceptions.AccountNotFound;
import common.exceptions.BadStringToParse;
import common.exceptions.ClientNotFound;
import objects.accounts.CuentaAhorro;
import objects.accounts.CuentaCorriente;
import objects.accounts.Persona;
import objects.accounts.PersonaJuridica;

/**
 *
 * @author jhose
 */
public class PanListaCuentas extends javax.swing.JPanel {

    DefaultTableModel mt = new DefaultTableModel();
    private Admin comp;
    /**
     * Creates new form PanListaEmpleados
     */
    public PanListaCuentas(Admin comp) {
        this.comp = comp;
        initComponents();
        String ids[] = {"Nombre","Apellidos","DNI","Telefono","Direccion","Coreo electronico","Sueldo"};
        mt.setColumnIdentifiers(ids);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        cmbAcc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpAccountInfo = new javax.swing.JTextPane();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccActionPerformed(evt);
            }
        });
        panBlanco.add(cmbAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, 40));

        jScrollPane1.setViewportView(txpAccountInfo);

        panBlanco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 580, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void cmbAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccActionPerformed
          
        String number = cmbAcc.getSelectedItem().toString();
		try {
			Cuenta account = comp.searchCuenta(number);
			if (number.charAt(0)=='1'){
				CuentaAhorro acct = (CuentaAhorro)account;
				txpAccountInfo.setText(acct.toString());
			}
			else {
				CuentaCorriente acct = (CuentaCorriente)account;
				txpAccountInfo.setText(acct.toString());
			}

		} catch (AccountNotFound | BadStringToParse e) {
			txpAccountInfo.setText("ERROR\nCuenta no encontrada");
		}
		cmbAcc.removeAllItems();
		for(String i : comp.getListaNrosCuenta()){
			cmbAcc.addItem(i);
		}
    }//GEN-LAST:event_cmbAccActionPerformed
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAcc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JTextPane txpAccountInfo;
    // End of variables declaration//GEN-END:variables
}
