/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesAdministrador;

import components.Admin;
import objects.accounts.Cuenta;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.swing.table.DefaultTableModel;

import common.exceptions.AccountNotFound;
import common.exceptions.BadStringToParse;
import common.logger.Logger;
import objects.accounts.CuentaAhorro;
import objects.accounts.CuentaCorriente;

/**
 *
 * @author jhose
 */
public class PanLogs extends javax.swing.JPanel {

    DefaultTableModel mt = new DefaultTableModel();
    private Admin comp;

    /**
     * Creates new form PanListaEmpleados
     */
    public PanLogs(Admin comp) {
        initComponents();
        String ids[] = {"Nombre", "Apellidos", "DNI", "Telefono", "Direccion", "Coreo electronico", "Sueldo"};
        mt.setColumnIdentifiers(ids);
        this.comp = comp;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpLog = new javax.swing.JTextPane();
        txtpath = new javax.swing.JTextField();
        btnRead = new javax.swing.JButton();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(txpLog);

        panBlanco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 700, 720));
        panBlanco.add(txtpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 40));

        btnRead.setText("Leer");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        panBlanco.add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        txpLog.setText("");
        for (String i : comp.getLog(txtpath.getText())) {
            txpLog.setText(txpLog.getText() + "\n" + i);
        }

    }//GEN-LAST:event_btnReadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRead;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JTextPane txpLog;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
