/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.operacionesAdministrador;

import components.Admin;
import objects.accounts.Cuenta;

import javax.swing.table.DefaultTableModel;

import common.exceptions.AccountNotFound;
import common.exceptions.BadStringToParse;
import common.exceptions.ClientNotFound;
import objects.accounts.CuentaAhorro;
import objects.accounts.CuentaCorriente;
import objects.accounts.Persona;
import objects.accounts.PersonaJuridica;

/**
 *
 * @author jhose
 */
public class PanListaClientes extends javax.swing.JPanel {

    private Admin comp;

    /**
     * Creates new form PanListaEmpleados
     */
    public PanListaClientes(Admin comp) {
        this.comp = comp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBlanco = new javax.swing.JPanel();
        cmbAcc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpClientInfo = new javax.swing.JTextPane();

        panBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panBlanco.setPreferredSize(new java.awt.Dimension(1140, 784));
        panBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        cmbAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccActionPerformed(evt);
            }
        });
        panBlanco.add(cmbAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, 40));

        jScrollPane1.setViewportView(txpClientInfo);

        panBlanco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 580, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccActionPerformed

        String number = cmbAcc.getSelectedItem().toString();
        try {
            if (number.length() == 8) {
                Persona account = comp.searchNatural(number);
                txpClientInfo.setText(account.toString());
            } else {
                PersonaJuridica account = comp.searchJuridica(number);
                txpClientInfo.setText(account.toString());
            }

        } catch (ClientNotFound e) {
            txpClientInfo.setText("ERROR\nCliente no encontrado");
        }
        cmbAcc.removeAllItems();
        for (String i : comp.getListaNrosDoc()) {
            cmbAcc.addItem(i);
        }
    }//GEN-LAST:event_cmbAccActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAcc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panBlanco;
    private javax.swing.JTextPane txpClientInfo;
    // End of variables declaration//GEN-END:variables
}
